<!DOCTYPE html>
<html>
    <head>
        <title>${title}</title>
        <meta charset="UTF-8"/>
        <style>
            #code_snippet {
                font-family: Geneva, Arial, Helvetica, sans-serif;
                font-size: 12px;
                background: #efefef;
                border: solid #868686 1px;
                padding: 10px 5px 10px 10px;
                width: 50%;
                min-height: 150px;
            }
        </style>
    </head>
    <body>
        <div id="code_snippet"><b>404. </b>Page not found</div>
    </body>
</html>